apiVersion: v1
kind: Service
metadata:
  name: back-bandas-service-{{.Values.deployment.environment}}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
