apiVersion: v1
kind: Service
metadata:
  name: db-service-{{.Values.deployment.environment}}
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
