apiVersion: v1
kind: Service
metadata:
  name: front-service-{{.Values.deployment.environment}}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
     #nodePort: {{ .Values.deployment.nodePort}}
