appName: frontend

deployment:
    replicaCount: 1
    nodePort: 30081
    environment: "prod" 
    host: "app-prod.com"
    image:
       tag: 20

configmap: 
  nginxConf: |-
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;
    
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
    
        location /api {
            proxy_pass http://back-service-prod.backend-prod:3000/;
        }

        location /banda {
            proxy_pass http://back-bandas-service-prod.backend-bandas-prod:3001/;
        }
        
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
