appName: frontend

deployment:
    replicaCount: 0
    nodePort: 30080
    environment: "dev"
    host: "app-dev.com"
    image:
       tag: 19
configmap: 
  nginxConf: |-
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;
    
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
    
        location /api {
            proxy_pass http://back-service-dev.backend-dev:3000/;
        }
        
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
