apiVersion: v1
kind: Service
metadata:
  name: nodejs-service-{{.Values.deployment.environment}}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
